# Production host-specific configuration
host_id = "production"

[overrides]
data_dir = "/opt/lazabot/data"
log_dir = "/opt/lazabot/logs"
log_level = "warn"
vault_path = "/opt/lazabot/data/credentials.vault"
database_url = "sqlite:///opt/lazabot/data/lazabot.db"

[overrides.api_endpoints]
base_url = "https://api.lazada.com"
timeout_seconds = 60
max_retries = 5

[overrides.proxy_settings]
enabled = true
health_check_interval = 180
rotation_enabled = true

[overrides.captcha_settings]
polling_interval = 3
max_attempts = 30
timeout_seconds = 60

[environment]
name = "production"
is_production = true
debug_enabled = false

[environment.env_vars]
LAZABOT_LOG_LEVEL = "warn"
LAZABOT_DATA_DIR = "/opt/lazabot/data"
LAZABOT_LOG_DIR = "/opt/lazabot/logs"
