# Ubuntu host-specific configuration
host_id = "ubuntu"

[overrides]
data_dir = "/opt/lazabot/data"
log_dir = "/opt/lazabot/logs"
log_level = "info"
vault_path = "/opt/lazabot/data/credentials.vault"
database_url = "sqlite:///opt/lazabot/data/lazabot.db"

[overrides.api_endpoints]
base_url = "https://api.lazada.com"
timeout_seconds = 30
max_retries = 3

[overrides.proxy_settings]
enabled = true
health_check_interval = 300
rotation_enabled = true

[overrides.captcha_settings]
polling_interval = 5
max_attempts = 60
timeout_seconds = 120

[environment]
name = "production"
is_production = true
debug_enabled = false

[environment.env_vars]
LAZABOT_LOG_LEVEL = "info"
LAZABOT_DATA_DIR = "/opt/lazabot/data"
LAZABOT_LOG_DIR = "/opt/lazabot/logs"
